package com.example.myapplication.utils;

import com.example.myapplication.reader.ODSReader;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

public class Utils {
    public static int parseInt(int yearColumn, Object[] v) {
        String strVal = ODSReader.getColumn(v, yearColumn);
        String replace = strVal.replace(".0", "");
        return Integer.parseInt(replace);
    }

    public static Map<String, String> populateNameMap() {
        var map = new HashMap<String, String>();

        map.putAll(generateEntries("Аарон", "Аренъ", "Аронъ"));
        map.putAll(generateEntries("Абдон", "Абдонъ"));
        map.putAll(generateEntries("Август", "Августъ"));
        map.putAll(generateEntries("Августин", "Августинъ"));
        map.putAll(generateEntries("Авксентий", "Авксентій"));
        map.putAll(generateEntries("Автоном", "Автономъ"));
        map.putAll(generateEntries("Агафон", "Агатонъ", "Агафонъ"));
        map.putAll(generateEntries("Адальберт", "Альберт", "Адальбертъ", "Альбертъ", "Войцех"));
        map.putAll(generateEntries("Адам", "Адамъ"));
        map.putAll(generateEntries("Адольф", "Адольфъ"));
        map.putAll(generateEntries("Адриан", "Адріанъ", "Адрианъ"));
        map.putAll(generateEntries("Александр", "Александръ"));
        map.putAll(generateEntries("Алексей", "Алексій", "Алексѣй"));
        map.putAll(generateEntries("Альбин", "Альбинъ"));
        map.putAll(generateEntries("Альфонс", "Альфонсъ"));
        map.putAll(generateEntries("Амбросий", "Амбросій"));
        map.putAll(generateEntries("Амос", "Аммосъ", "Амосъ,"));
        map.putAll(generateEntries("Анастасий", "Анастасій"));
        map.putAll(generateEntries("Анатолий", "Анатолій"));
        map.putAll(generateEntries("Андрей", "Андрий", "Андрій", "Андрѣй"));
        map.putAll(generateEntries("Андроник", "Андроникъ"));
        map.putAll(generateEntries("Ансельм", " Анзельмъ"));
        map.putAll(generateEntries("Aникита", "Аникитъ"));
        map.putAll(generateEntries("Антон", "Антонъ", "Антоній"));
        map.putAll(generateEntries("Аполлинарий", "Аполинаръ", "Аполинарій", "Аполлинарій", "Апполлинарій"));
        map.putAll(generateEntries("Апполон", "Аполлонъ", "Аполонъ", "Апполонъ"));
        map.putAll(generateEntries("Апполоний", "Апполоній"));
        map.putAll(generateEntries("Арефа", "Арефъ"));
        map.putAll(generateEntries("Аристрах", "Аристархъ"));
        map.putAll(generateEntries("Аркадий", "Аркадій"));
        map.putAll(generateEntries("Арсений", "Арсеній"));
        map.putAll(generateEntries("Артемий", "Артемій", "Артемъ"));
        map.putAll(generateEntries("Архип", "Архипъ"));
        map.putAll(generateEntries("Афанасий", "Афанасій", "Аѳанасій,"));
        map.putAll(generateEntries("Африкан", "Африканъ"));
        map.putAll(generateEntries("Бальтазар", "Валтазаръ"));
        map.putAll(generateEntries("Богдан", "Федот", "Богданъ", "Ѳеодотъ"));
        map.putAll(generateEntries("Богуслав", "Богуславъ"));
        map.putAll(generateEntries("Болеслав", "Болеславъ"));
        map.putAll(generateEntries("Борис", "Борисъ"));
        map.putAll(generateEntries("Бронислав", "Брониславъ"));
        map.putAll(generateEntries("Вадим", "Вадимъ"));
        map.putAll(generateEntries("Валентин", "Валентинъ", "Валентій"));
        map.putAll(generateEntries("Валерий", "Валерій"));
        map.putAll(generateEntries("Валерьян", "Валеріанъ", "Валеріянъ"));
        map.putAll(generateEntries("Вальдемар", "Вальдемаръ"));
        map.putAll(generateEntries("Василий", "Василиій", "Василь", "Василіи", "Василіий", "Василій"));
        map.putAll(generateEntries("Вацлав", "Вячеслав", "Вацлавъ", "Вячеславъ"));
        map.putAll(generateEntries("Велизар", "Велизарій"));
        map.putAll(generateEntries("Венедикт", "Венедиктъ"));
        map.putAll(generateEntries("Вениамин", "Вениаминъ", "Веніаминъ"));
        map.putAll(generateEntries("Викентий", "Вікентій", "Викентій"));
        map.putAll(generateEntries("Виктор", "Викторъ"));
        map.putAll(generateEntries("Вильгельм", "Вильгельмъ"));
        map.putAll(generateEntries("Виссарион", "Виссаріонъ"));
        map.putAll(generateEntries("Виталий", "Виталій"));
        map.putAll(generateEntries("Витольд", "Витольдъ"));
        map.putAll(generateEntries("Владимир", "Владимиръ", "Владиміръ", "Володиміръ"));
        map.putAll(generateEntries("Владислав", "Владыславъ"));
        map.putAll(generateEntries("Всеволод", "Всеволодъ"));
        map.putAll(generateEntries("Гаврила", "Гавріилъ"));
        map.putAll(generateEntries("Гаспар", "Гасперъ", "Касперъ"));
        map.putAll(generateEntries("Гаэтано", "Каетанъ"));
        map.putAll(generateEntries("Гедеон", "Гедеонъ"));
        map.putAll(generateEntries("Геннадий", "Генадій", "Геннадій"));
        map.putAll(generateEntries("Генрих", "Генрихъ", "Генрікъ", "Генріхъ"));
        map.putAll(generateEntries("Георгий", "Георгій", "Егоръ", "Юрій"));
        map.putAll(generateEntries("Герасим", "Герасимъ"));
        map.putAll(generateEntries("Гервасий", "Гервасій"));
        map.putAll(generateEntries("Герман", "Германъ"));
        map.putAll(generateEntries("Глеб", "Глюбъ", "Глѣбъ"));
        map.putAll(generateEntries("Григорий", "Грегорій", "Григорій"));
        map.putAll(generateEntries("Давыд", "Давидъ"));
        map.putAll(generateEntries("Дамаскин", "Дамаскинъ"));
        map.putAll(generateEntries("Данила", "Даніилъ", "Данійло", "Даніллъ"));
        map.putAll(generateEntries("Дементий", "Деметій"));
        map.putAll(generateEntries("Денис", "Діонизій", "Діонисій"));
        map.putAll(generateEntries("Демьян", "Демьянъ"));
        map.putAll(generateEntries("Дмитрий", "Димитръ", "Димитрій", "Дмитрій"));
        map.putAll(generateEntries("Доместиан", "Доместіанъ"));
        map.putAll(generateEntries("Дометий", "Дометій"));
        map.putAll(generateEntries("Доминик", "Доминикъ"));
        map.putAll(generateEntries("Донат", "Донатъ"));
        map.putAll(generateEntries("Дормидонт", "Доримедонтъ"));
        map.putAll(generateEntries("Еварест", "Еварестъ"));
        map.putAll(generateEntries("Евгений", "Евгеній"));
        map.putAll(generateEntries("Евграф", "Евграфъ"));
        map.putAll(generateEntries("Евдоким", "Евдокимъ"));
        map.putAll(generateEntries("Евалампий", "Евлампій"));
        map.putAll(generateEntries("Евсей", "Евсений"));
        map.putAll(generateEntries("Евстафий", "Евстафій", "Евстаѳій"));
        map.putAll(generateEntries("Елевферий", "Елевтерій", "Елевѳерій"));
        map.putAll(generateEntries("Емельян", "Емельянъ", "Емилианъ", "Емильянъ", "Емілянъ"));
        map.putAll(generateEntries("Епифан", "Епифаній"));
        map.putAll(generateEntries("Ерофей", "Іероѳей"));
        map.putAll(generateEntries("Ермил", "Ермилъ"));
        map.putAll(generateEntries("Ефим", "Ефимъ"));
        map.putAll(generateEntries("Евсей", "Еѳсеній"));
        map.putAll(generateEntries("Захар", "Захарій"));
        map.putAll(generateEntries("Збигнев", "Збигневъ", "Збигнѣв"));
        map.putAll(generateEntries("Зиновий", "Зеновій", "Зиновій"));
        map.putAll(generateEntries("Зинон", "Зенонъ"));
        map.putAll(generateEntries("Иакинф", "Іоакинфъ", "Якинф"));
        map.putAll(generateEntries("Иван", "Іоаннъ", "Іоанъ", "Иванъ"));
        map.putAll(generateEntries("Игнатий", "Игнатъ", "Игнатій", "Ігнатій"));
        map.putAll(generateEntries("Игорь", "Игоръ", "Игор"));
        map.putAll(generateEntries("Иерон", "Иеронъ"));
        map.putAll(generateEntries("Иларион", "Иларіонъ", "Іларіонъ"));
        map.putAll(generateEntries("Иларий", "Гиляріи"));
        map.putAll(generateEntries("Ильдефонс", "Ильдефонсъ"));
        map.putAll(generateEntries("Илья", "Илія"));
        map.putAll(generateEntries("Иммануиль", "Еммануилъ", "Мануилъ"));
        map.putAll(generateEntries("Иннокентий", "Иннокентій"));
        map.putAll(generateEntries("Иаоким", "Іоакимъ", "Якимъ", "Екимъ"));
        map.putAll(generateEntries("Иоанникий", "Іоанникій", "Йоанникъ"));
        map.putAll(generateEntries("Иосиф", "Иосифъ", "Осипъ", "Іосифъ", "Юзефъ", "Юзеф"));
        map.putAll(generateEntries("Ипполит", "Ипполить"));
        map.putAll(generateEntries("Иринарх", "Иринархъ"));
        map.putAll(generateEntries("Иероним", "Иронимъ", "Іронимъ", "Іеронимъ", "Еронимъ,"));
        map.putAll(generateEntries("Иона", "Іона"));
        map.putAll(generateEntries("Иосафат", "Іоасафать", "Іоасафъ", "Іоассафъ", "Іосафатъ", "Іосафъ,"));
        map.putAll(generateEntries("Исидор", "Исидоръ", "Ісидоръ"));
        map.putAll(generateEntries("Измаил", "Исмаилъ", "Измаилъ"));
        map.putAll(generateEntries("Иошер", "Іошеръ", "Иошеръ"));
        map.putAll(generateEntries("Казимир", "Казимиръ", "Казиміръ"));
        map.putAll(generateEntries("Каликст", "Каликстъ"));
        map.putAll(generateEntries("Каллистрат", "Калистратъ", "Каллистратъ"));
        map.putAll(generateEntries("Кандид", "Кандитъ", "Кандидъ"));
        map.putAll(generateEntries("Каллисфен", "Калисѳенъ"));
        map.putAll(generateEntries("Капитон", "Капитонъ"));
        map.putAll(generateEntries("Карл", "Карлъ"));
        map.putAll(generateEntries("Келестин", "Келестинъ"));
        map.putAll(generateEntries("Кесарий", "Кесарій", "Кессарій,"));
        map.putAll(generateEntries("Куприян", "Кипрянъ", "Кипріанъ", "Кипріянъ"));
        map.putAll(generateEntries("Кирилл", "Кириллъ"));
        map.putAll(generateEntries("Клавдий", "Клавдій"));
        map.putAll(generateEntries("Клеоник", "Клеоникъ"));
        map.putAll(generateEntries("Климент", "Клементій", "Климентъ", "Климентій", "Кліментъ", "Кліменті", "Климъ"));
        map.putAll(generateEntries("Клит", "Клитъ"));
        map.putAll(generateEntries("Кондрат", "Кондратий"));
        map.putAll(generateEntries("Конкордий", "Конкордій"));
        map.putAll(generateEntries("Константин", "Константинъ"));
        map.putAll(generateEntries("Корнилий", "Корнелій", "Корнилій"));
        map.putAll(generateEntries("Ксаверий", "Ксаверій"));
        map.putAll(generateEntries("Ксенофонт", "Ксенофонтъ"));
        map.putAll(generateEntries("Кузьма", "Косьма"));
        map.putAll(generateEntries("Лавр", "Лавръ", "Лауръ"));
        map.putAll(generateEntries("Лаврентий", "Лаврентій"));
        map.putAll(generateEntries("Лев", "Левъ"));
        map.putAll(generateEntries("Леонард", "Леонардъ"));
        map.putAll(generateEntries("Леонид", "Леонидъ", "Леонідъ"));
        map.putAll(generateEntries("Леонтий", "Леонтій", "Леонъ", "Леон"));
        map.putAll(generateEntries("Леопольд", "Леопольдъ"));
        map.putAll(generateEntries("Лонгин", "Лонгинъ"));
        map.putAll(generateEntries("Лукьян", "Лукиянъ", "Лукіан", "Лукиан"));
        map.putAll(generateEntries("Любомир", "Любомиръ"));
        map.putAll(generateEntries("Макар", "Макарій"));
        map.putAll(generateEntries("Максим", "Максимъ"));
        map.putAll(generateEntries("Максимилиан", "Максимиліанъ-Лудовикъ", "Максимиліанъ-Юліанъ", "Максимилианъ"));
        map.putAll(generateEntries("Мариан  Марианъ", "Маріанъ"));
        map.putAll(generateEntries("Марин", "Маринъ"));
        map.putAll(generateEntries("Марк", "Маркъ"));
        map.putAll(generateEntries("Маркел", "Маркеллъ"));
        map.putAll(generateEntries("Маркиан", "Маркіанъ"));
        map.putAll(generateEntries("Мартин", "Мартинъ"));
        map.putAll(generateEntries("Матвей", "Матвѣй", "Матфей", "Матѳей"));
        map.putAll(generateEntries("Мелетий", "Мелентій"));
        map.putAll(generateEntries("Мелхиседек", "Мелхиседекъ"));
        map.putAll(generateEntries("Мефодий", "Мефодій", "Меѳодій"));
        map.putAll(generateEntries("Мирон", "Миронъ"));
        map.putAll(generateEntries("Митрофан", "Митрофанъ"));
        map.putAll(generateEntries("Михаил", "Михаило", "Михаилъ", "Михайло"));
        map.putAll(generateEntries("Модест", "Модестъ"));
        map.putAll(generateEntries("Наполеон", "Наполеонъ"));
        map.putAll(generateEntries("Наркис", "Наркизъ", "Наркиссъ", "Наркисъ"));
        map.putAll(generateEntries("Нестор", "Несторъ"));
        map.putAll(generateEntries("Никандр", "Никандръ"));
        map.putAll(generateEntries("Никанор", "Никаноръ"));
        map.putAll(generateEntries("Никифор", "Никифоръ"));
        map.putAll(generateEntries("Никодим", "Никодемъ", "Никодимъ"));
        map.putAll(generateEntries("Нил", "Нилъ"));
        map.putAll(generateEntries("Олег", "Олегъ"));
        map.putAll(generateEntries("Олимпий", "Олимпій"));
        map.putAll(generateEntries("Онисим", "Онисимъ"));
        map.putAll(generateEntries("Онуфрий", "Онуфрій", "Онуѳрій"));
        map.putAll(generateEntries("Оттоне", "Оттонъ"));
        map.putAll(generateEntries("Павел", "Павелъ", "Павелъ-Юліанъ"));
        map.putAll(generateEntries("Палладий", "Палладій"));
        map.putAll(generateEntries("Пантелеймон", "Панталимонъ", "Пантелеимонъ"));
        map.putAll(generateEntries("Патапий,Потапий", "Потапій"));
        map.putAll(generateEntries("Парфений", "Парфеній", "Парфирій", "Парѳеній"));
        map.putAll(generateEntries("Пётр", "Петръ", "Петро"));
        map.putAll(generateEntries("Плакид", "Плакидъ"));
        map.putAll(generateEntries("Платон", "Платонъ"));
        map.putAll(generateEntries("Поликарп", "Поликарпъ"));
        map.putAll(generateEntries("Порфирий", "Порфирій"));
        map.putAll(generateEntries("Прокофий", "Прокофій"));
        map.putAll(generateEntries("Протасий", "Протасій"));
        map.putAll(generateEntries("Прохор", "Прохоръ"));
        map.putAll(generateEntries("Рафаил", "Рафаилъ"));
        map.putAll(generateEntries("Ричард", "Ричардъ"));
        map.putAll(generateEntries("Роман", "Романъ"));
        map.putAll(generateEntries("Ромуальд", "Ромуалдъ", "Ромуальдъ"));
        map.putAll(generateEntries("Ростислав", "Ростиславъ"));
        map.putAll(generateEntries("Руф", "Руфъ"));
        map.putAll(generateEntries("Савва", "Саавва", "Саава"));
        map.putAll(generateEntries("Савватий", "Савватій"));
        map.putAll(generateEntries("Савин", "Саввинъ"));
        map.putAll(generateEntries("Савелий", "Савелій"));
        map.putAll(generateEntries("Самсон", "Сампсонъ", "Самсонъ"));
        map.putAll(generateEntries("Самуил", "Замель"));
        map.putAll(generateEntries("Севастьян", "Севастіанъ"));
        map.putAll(generateEntries("Севериан", "Северіанъ", "Северіянъ"));
        map.putAll(generateEntries("Северин", "Северинъ"));
        map.putAll(generateEntries("Семён", "Семенъ", "Семёнъ", "Симеонъ", "Симонъ", "Сімеонъ", "Семен"));
        map.putAll(generateEntries("Серапион", "Серапіонъ"));
        map.putAll(generateEntries("Серафим", "Серафимъ"));
        map.putAll(generateEntries("Сергей", "Сергій", "Сергѣй"));
        map.putAll(generateEntries("Сильвестр", "Сильвестеръ", "Сильвестръ,"));
        map.putAll(generateEntries("Симплиций", "Симплицій"));
        map.putAll(generateEntries("Созонт", "Созонтъ", "Созонъ"));
        map.putAll(generateEntries("Софроний", "Софроній", "Сафроній", "Софронт"));
        map.putAll(generateEntries("Станислав", "Станиславъ"));
        map.putAll(generateEntries("Степан", "Степанъ", "Стефанъ"));
        map.putAll(generateEntries("Тарас", "Тарасъ"));
        map.putAll(generateEntries("Тимон", "Тимонъ"));
        map.putAll(generateEntries("Тимофей", "Тимоѳей"));
        map.putAll(generateEntries("Тит", "Титъ"));
        map.putAll(generateEntries("Тихон", "Тихонъ"));
        map.putAll(generateEntries("Трофим", "Трофимъ"));
        map.putAll(generateEntries("Фабиан", "Ѳабіянъ"));
        map.putAll(generateEntries("Фавст", "Фавстъ", "Ѳавстъ"));
        map.putAll(generateEntries("Фадей", "Фаддей", "Ѳаддей", "Ѳадей"));
        map.putAll(generateEntries("Фаустин", "Фаустинъ"));
        map.putAll(generateEntries("Феликс", "Феликсъ", "Фелліксъ", "Ѳеликсъ,"));
        map.putAll(generateEntries("Фелициан", "Фелиціанъ", "Феліцянъ", "Феліціанъ", "Ѳеліціанъ"));
        map.putAll(generateEntries("Фёдор", "Феодоръ", "Ѳедоръ", "Ѳеодоръ", "Федоръ"));
        map.putAll(generateEntries("Федосий", "Феодосій", "Ѳеодосій"));
        map.putAll(generateEntries("Феофил", "Феофилъ", "Ѳеофилъ", "Теофилъ,"));
        map.putAll(generateEntries("Фердинанд", "Фердинандъ"));
        map.putAll(generateEntries("Филарет", "Филаретъ"));
        map.putAll(generateEntries("Филимон", "Филимонъ"));
        map.putAll(generateEntries("Филипп", "Филиппъ", "Филипъ"));
        map.putAll(generateEntries("Филофей", "Филоѳей"));
        map.putAll(generateEntries("Флор", "Флоръ"));
        map.putAll(generateEntries("Фома", "Ѳома"));
        map.putAll(generateEntries("Фортунат", "Фортунатъ"));
        map.putAll(generateEntries("Фотий", "Фотій"));
        map.putAll(generateEntries("Франциск", "Францискъ", "Францъ", "Ѳранцъ"));
        map.putAll(generateEntries("Хлодвиг", "Лудвикъ", "Лудовикъ", "Людвикъ", "Людовикъ", "Людовик"));
        map.putAll(generateEntries("Хрисанф", "Хрисанфъ"));
        map.putAll(generateEntries("Эдуард", "Едуардъ", "Эдуардъ"));
        map.putAll(generateEntries("Эраст", "Едуардъ", "Эдуардъ"));
        map.putAll(generateEntries("Эразм", "Еразмъ", "Ерасмъ"));
        map.putAll(generateEntries("Юлиан", "Юляіанъ", "Юліянъ", "Юліанъ", "Юлянъ", "Юльянъ", "Іуліанъ", "Іуліянъ"));
        map.putAll(generateEntries("Юлий", "Юлій"));
        map.putAll(generateEntries("Юстин", "Юстинъ", "Юстінъ", "Устинъ", "Іустинъ"));
        map.putAll(generateEntries("Якинф", "Якинфъ"));
        map.putAll(generateEntries("Яков", "Яковъ,"));
        map.putAll(generateEntries("Януарий", "Яннуарій", "Януарій", "Іаннуарій", "Ианнурий"));
        map.putAll(generateEntries("Ярослав", "Ярославъ"));

        return map;
    }

    private static Map<String, String> generateEntries(String... names) {
        return Arrays.stream(names).collect(Collectors.toMap(n -> n, n -> names[0]));
    }
}
